### ISSUE TITLE
Error: spawn bin/td-linux-x64 ENOENT

### ISSUE THREAD

**Issue by qustrolabe** [sirussu/open-launcher#1]
Судя по выводу лаунчер не может скачать торрент файл.
Запускал на Ubuntu 20.04 LTS x86_64 
`

~ $ ./SirusLauncher-1.2.12-test.AppImage
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
[01:17:09.558] [info] Run with [ '/tmp/.mount_SirusLbw2WlQ/siruslauncher' ]
[01:17:09.660] [info] Checking for update
[01:17:12.676] [info] acc id null
[01:17:12.785] [info] Update for version 1.2.12-test is not available (latest version: 1.2.12-test, downgrade is disallowed).
[01:17:12.788] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[01:17:14.573] [info] bin/td-linux-x64 [
  'torrent',
  '/home/nathman/.config/Sirus Launcher/sirus.torrent',
  '/home/nathman/wow'
]
[01:17:14.583] [error] Error: spawn bin/td-linux-x64 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[01:17:14.591] [error] wt-error {
  error: {
    code: 'ENOENT',
    errno: 'ENOENT',
    path: 'bin/td-linux-x64',
    spawnargs: [
      'torrent',
      '/home/nathman/.config/Sirus Launcher/sirus.torrent',
      '/home/nathman/wow'
    ],
    syscall: 'spawn bin/td-linux-x64'
  },
  repeat: true
}
`

**Comment by avengerweb** [comment]
Конкретно эта проблема исправлена, но загрузка торрента для линукса почему то не работает, пока не разобрался, не может подключится к сидам.

**Comment by Diez37** [comment]
версия лаунчера - 1.3.1
ОС - ubuntu 22.04

в логах всплывает вот такая шняга ((
```shell
[error] /tmp/.mount_SirusLuP96TP/resources/app.asar.unpacked/node_modules/@sirussu/torrent-downloader/vendor/td-linux-x64/td-linux-x64: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by qustrolabe** [comment]
> версия лаунчера - 1.3.1 ОС - ubuntu 22.04
> 
> в логах всплывает вот такая шняга ((
> 
> ```shell
> [error] /tmp/.mount_SirusLuP96TP/resources/app.asar.unpacked/node_modules/@sirussu/torrent-downloader/vendor/td-linux-x64/td-linux-x64: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
> ```

```bash
sudo apt-get install libssl-dev
```

Дальше наверняка ещё какую-то либу не найдёт, поэтому сразу гугли где и как её установить

**Comment by Diez37** [comment]
если бы все было так просто)) я бы не написал))

```shell
diez37@diez37-Legion-5-Pro-16ITH6:~$ sudo apt-get install libssl-dev
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет libssl-dev самой новой версии (3.0.2-0ubuntu1.1).
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 25 пакетов не обновлено.
diez37@diez37-Legion-5-Pro-16ITH6:~$ cd ./wow/
diez37@diez37-Legion-5-Pro-16ITH6:~/wow$ ./SirusLauncher-1.3.1.AppImage 
[13:06:19.183] [info] Run with [ '/tmp/.mount_SirusL4dFX52/siruslauncher' ]
[13:06:19.193] [info] Checking for update
[13:06:19.666] [info] acc id null
[13:06:20.093] [info] /tmp/.mount_SirusL4dFX52/resources/app.asar.unpacked/node_modules/@sirussu/torrent-downloader/vendor/td-linux-x64/td-linux-x64 [
  'torrent',
  '/home/diez37/.config/Sirus Launcher/sirus.torrent',
  '/home/diez37/wow/install'
]
[13:06:20.099] [error] /tmp/.mount_SirusL4dFX52/resources/app.asar.unpacked/node_modules/@sirussu/torrent-downloader/vendor/td-linux-x64/td-linux-x64: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

[13:06:20.099] [warn] Process exit with 127
[13:06:20.100] [error] wt-error { repeat: false, processExitWithError: true, isDisabled: false }
[13:06:23.324] [info] Update for version 1.3.1 is not available (latest version: 1.3.1, downgrade is disallowed).
[13:06:23.324] [debug] checkForUpdatesAndNotify called, downloadPromise is null
^Cdiez37@diez37-Legion-5-Pro-16ITH6:~/wow$ 
```

**Comment by Diez37** [comment]
етить, мало ли кому понадобиться.

зависимости просто старенькие, на старых либах крутяться
по ubuntu/debian можно взять вот эту либу 
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.17_amd64.deb

в ней леижит либа нужной версии, после установки, у меня все завелось
как клиент скачаю, если будут траблы, напишу
